"""empty message

Revision ID: 085caf773e6b
Revises: 
Create Date: 2023-09-28 12:33:04.446380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085caf773e6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isGay', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isGay')

    # ### end Alembic commands ###
